# AMBARELLA Platform Support
snd-soc-ambarella-objs := ambarella_pcm.o
snd-soc-ambarella-i2s-objs := ambarella_i2s.o
snd-soc-ambarella-dmic-objs := ambarella_dmic.o

obj-$(CONFIG_SND_AMBARELLA_SOC)		+= snd-soc-ambarella.o
obj-$(CONFIG_SND_AMBARELLA_SOC_I2S)	+= snd-soc-ambarella-i2s.o
obj-$(CONFIG_SND_AMBARELLA_SOC_DMIC)	+= snd-soc-ambarella-dmic.o

