# Title: Dockerfile for building the EVE kernel
VERSION=$(shell git rev-parse --short=12 HEAD)
DIRTY=$(shell git diff --quiet || echo '-dirty')
EVE_FLAVOR=generic
ARCHITECTURE=arm64
KERNEL_TAG=v6.1.112
PLATFORM=linux/$(ARCHITECTURE)
BUILD_USER:=$(shell id -un)

IMAGE_REPOSITORY?=lfedge/eve-kernel

LINUXKIT_VERSION=58c36c9eb0c32acf66ae7877d18a9ad24d59d73e
GOBIN=/tmp/linuxkit-$(LINUXKIT_VERSION)
LK=$(GOBIN)/linuxkit

BUILD_KIT_VERSION=v0.12.5
BUILD_KIT_BUILDER=eve-kernel-builder-$(BUILD_KIT_VERSION)

# TLS-intercepting proxy support; all no-ops when empty. See ../tools/misc/ca/README.md.
CA_CERTS_DIR?=$(CURDIR)/../tools/misc/ca
CA_CERTS=$(wildcard $(CA_CERTS_DIR)/*.crt)
ifeq ($(CA_CERTS),)
BUILD_KIT_IMAGE=moby/buildkit:$(BUILD_KIT_VERSION)
EXTRA_CA_CERTS_ARG=
else
BUILD_KIT_IMAGE=moby/buildkit:$(BUILD_KIT_VERSION)-localca
EXTRA_CA_CERTS_ARG=--build-arg="EXTRA_CA_CERTS=$$(cat $(CA_CERTS))"
endif

SOURCE_DATE_EPOCH=$(shell git log -1 --format=%ct)
BRANCH=eve-kernel-$(ARCHITECTURE)-$(KERNEL_TAG)-$(EVE_FLAVOR)
# make sure we get a date in correct format, otherwise initramfs cpio mtime will be variable
KBUILD_BUILD_TIMESTAMP=$(shell git log -1 --format=%cd | cut -f1 -d"+")

ifeq ($(BUILDKIT_PROGRESS),)
    export BUILDKIT_PROGRESS := plain
endif

# if BRANCH is defined on a command line we are running under CI
# we add user name to DIRTY to avoid docker tag conflicts
# when building on a shared machine with shared docker cache
ifeq ($(origin BRANCH), file)
	DIRTY:=-$(BUILD_USER)$(DIRTY)
endif

.PHONY: all help

all: kernel-gcc

help: Makefile
	@echo
	@echo "Makefile to build EVE kernel"
	@echo "Usage: make [target]"
	@echo "Targets:"
	@echo "  kernel-gcc: build kernel with gcc"
	@echo "  kernel-clang: build kernel with clang"
	@echo "  docker-tag-gcc: print docker tag for gcc kernel"
	@echo "  docker-tag-clang: print docker tag for clang kernel"
	@echo "  push-gcc: push gcc kernel to docker.io"
	@echo "  push-clang: push clang kernel to docker.io"
	@echo "  clean: remove generated files"
	@echo

.PHONY: buildkit-ca-image
buildkit-ca-image:
ifneq ($(CA_CERTS),)
	@$(CA_CERTS_DIR)/mkbuildkit.sh $(BUILD_KIT_VERSION) $(BUILD_KIT_IMAGE)
endif

.PHONY: ensure-builder
ensure-builder: buildkit-ca-image
	docker buildx inspect $(BUILD_KIT_BUILDER) 2>/dev/null || \
	docker buildx create --name $(BUILD_KIT_BUILDER) \
	--driver docker-container --bootstrap --driver-opt=image=$(BUILD_KIT_IMAGE)

.PHONY: linuxkit
linuxkit: $(LK)
$(LK):
	GOBIN=$(GOBIN) go install github.com/linuxkit/linuxkit/src/cmd/linuxkit@$(LINUXKIT_VERSION)

KERNEL_OCI_FILE:=$(shell mktemp -u)-kernel.tar

BUILD_CONTEXT_ARGS=
ifneq ($(wildcard ../drivers/cavalry),)
    BUILD_CONTEXT_ARGS += --build-context cavalry=../drivers/cavalry
else ifneq ($(wildcard ../cavalry),)
    BUILD_CONTEXT_ARGS += --build-context cavalry=../cavalry
endif
ifneq ($(wildcard ../drivers/amba_virt),)
    BUILD_CONTEXT_ARGS += --build-context amba-virt=../drivers/amba_virt
else ifneq ($(wildcard ../poc/kmod),)
    BUILD_CONTEXT_ARGS += --build-context amba-virt=..
else ifneq ($(wildcard ../../amba-virt),)
    BUILD_CONTEXT_ARGS += --build-context amba-virt=../../amba-virt
endif
ifneq ($(wildcard ../drivers/amba_otp),)
    BUILD_CONTEXT_ARGS += --build-context amba_otp=../drivers/amba_otp
else ifneq ($(wildcard ../amba_otp),)
    BUILD_CONTEXT_ARGS += --build-context amba_otp=../amba_otp
endif
ifneq ($(wildcard ../drivers/dsplog),)
    BUILD_CONTEXT_ARGS += --build-context dsplog=../drivers/dsplog
else ifneq ($(wildcard ../dsplog),)
    BUILD_CONTEXT_ARGS += --build-context dsplog=../dsplog
endif
ifneq ($(wildcard ../drivers/pci_platform),)
    BUILD_CONTEXT_ARGS += --build-context pci_platform=../drivers/pci_platform
else ifneq ($(wildcard ../pci_platform),)
    BUILD_CONTEXT_ARGS += --build-context pci_platform=../pci_platform
endif
ifneq ($(wildcard ../drivers/ambvideo),)
    BUILD_CONTEXT_ARGS += --build-context ambvideo=../drivers/ambvideo
else ifneq ($(wildcard ../ambvideo),)
    BUILD_CONTEXT_ARGS += --build-context ambvideo=../ambvideo
endif
ifneq ($(wildcard ../drivers/pwr_gpu),)
    BUILD_CONTEXT_ARGS += --build-context pwr_gpu=../drivers/pwr_gpu
else ifneq ($(wildcard ../pwr_gpu),)
    BUILD_CONTEXT_ARGS += --build-context pwr_gpu=../pwr_gpu
endif


kernel-build-%: Makefile.eve linuxkit | ensure-builder
	@echo "Building kernel version $(BRANCH):$(VERSION)-$* with compiler $*"
	docker buildx build \
	--builder=$(BUILD_KIT_BUILDER) \
	--build-arg="SOURCE_DATE_EPOCH=$(SOURCE_DATE_EPOCH)" \
	--build-arg="KBUILD_BUILD_TIMESTAMP=$(KBUILD_BUILD_TIMESTAMP)" \
	--build-arg="LOCALVERSION=$(VERSION)$(DIRTY)" \
	$(EXTRA_CA_CERTS_ARG) \
	$(BUILD_CONTEXT_ARGS) \
	--platform $(PLATFORM) -t $(IMAGE_REPOSITORY):$(BRANCH)-$(VERSION)$(DIRTY)-$* \
	--sbom=true --output=type=oci,dest=$(KERNEL_OCI_FILE) -f Dockerfile.$* .
	$(LK) cache import $(KERNEL_OCI_FILE)
	rm -f $(KERNEL_OCI_FILE)


# we need these intermediate targets to make .PHONY work for pattern rules
kernel-gcc: kernel-build-gcc
kernel-clang: kernel-build-clang
kernel-ambarella: kernel-build-ambarella
docker-tag-gcc: docker-tag-generate-gcc
docker-tag-clang: docker-tag-generate-clang
docker-tag-ambarella: docker-tag-generate-ambarella
push-gcc: push-image-gcc
push-clang: push-image-clang
push-ambarella: push-image-ambarella

clean-gcc: clean-image-gcc
clean-clang: clean-image-clang
clean-ambarella: clean-image-ambarella

.PHONY: kernel-gcc kernel-clang kernel-ambarella docker-tag-gcc docker-tag-clang docker-tag-ambarella push-gcc push-clang push-ambarella clean-gcc clean-clang clean-ambarella

docker-tag-generate-%:
	@echo "docker.io/$(IMAGE_REPOSITORY):$(BRANCH)-$(VERSION)$(DIRTY)-$*"

push-image-%:
	$(if $(DIRTY), $(error "Not pushing since the repo is dirty"))
	$(LK) cache push $(IMAGE_REPOSITORY):$(BRANCH)-$(VERSION)-$*

clean-image-%:
	$(LK) cache rm $(IMAGE_REPOSITORY):$(BRANCH)-$(VERSION)$(DIRTY)-$* 2>/dev/null || true
	docker rmi $(IMAGE_REPOSITORY):$(BRANCH)-$(VERSION)$(DIRTY)-$* 2>/dev/null || true

.PHONY: clean
clean:
	$(LK) cache clean
