# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2004-2023, Ambarella, Inc.

obj-$(CONFIG_BLAZENET)	+= blazenet.o
obj-$(CONFIG_RPMSG_AMBARELLA)	+= rpmsg_ambarella.o
obj-$(CONFIG_RPMSG_SLAVE_BUS)	+= rpmsg_slave_bus.o
obj-$(CONFIG_RPMSG_SLAVE_NS)	+= rpmsg_slave_ns.o
