--- drivers/clk/Makefile
+++ drivers/clk/Makefile
@@ -77,6 +77,7 @@ obj-$(CONFIG_COMMON_CLK_VC5)          += clk-versaclock5.o
 obj-$(CONFIG_COMMON_CLK_VC7)           += clk-versaclock7.o
 obj-$(CONFIG_COMMON_CLK_WM831X)                += clk-wm831x.o
 obj-$(CONFIG_COMMON_CLK_XGENE)         += clk-xgene.o
+obj-$(CONFIG_ARCH_AMBARELLA)           += ambarella/
 
 # please keep this section sorted lexicographically by directory path name
 obj-y                                  += actions/
