# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026, Ambarella International LLC.
#

obj-$(CONFIG_ARCH_AMBARELLA) += soc.o iav_helper.o syncproc.o io.o
obj-$(CONFIG_AMBARELLA_LPDDR5_ADJUST) += lpddr5_adjust.o
obj-y += pcie/
