#
# Makefile for ambarella specific clk
#

obj-y += clk-pll-common.o clk-pll-normal.o clk-composite.o clk-fixed-factor.o clk-misc.o
obj-y += hdmi/clk-pll-hdmi.o hdmi/clk-pll-hdmi-14nm.o hdmi/clk-pll-hdmi-regular.o

