--- drivers/pinctrl/Makefile
+++ drivers/pinctrl/Makefile
@@ -27,6 +27,7 @@ obj-$(CONFIG_PINCTRL_INGENIC) += pinctrl-ingenic.o
 obj-$(CONFIG_PINCTRL_K210)     += pinctrl-k210.o
 obj-$(CONFIG_PINCTRL_KEEMBAY)  += pinctrl-keembay.o
 obj-$(CONFIG_PINCTRL_LANTIQ)   += pinctrl-lantiq.o
+obj-$(CONFIG_PINCTRL_AMB)      += pinctrl-ambarella.o
 obj-$(CONFIG_PINCTRL_FALCON)   += pinctrl-falcon.o
 obj-$(CONFIG_PINCTRL_XWAY)     += pinctrl-xway.o
 obj-$(CONFIG_PINCTRL_LPC18XX)  += pinctrl-lpc18xx.o
